name: âœ… check
on: push
jobs:
  lint:
    name: ğŸ§¹lint
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: âš™ï¸ Install jsonlint
        run: |
          brew install jsonlint | tee
      - name: ğŸ§¹ Manifest Lint
        run: |
          cat manifest.json | jsonlint
      - name: âš™ï¸ Install swiftlint
        run: |
          if [ -z "$(which swiftlint)" ]; then
            brew install swiftlint
          else
            swiftlint version  
          fi
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: ğŸ§¹ Code Lint
        run: |
          if [ ! -f ".swiftlint.yml" ]; then
            curl -L https://raw.githubusercontent.com/4d-for-ios/check-workflow/master/form/quality/.swiftlint.yml --output .swiftlint.yml
          fi
          swiftlint --strict
  build:
      name: ğŸ— build
      runs-on: macos-latest
      env:
        RELEASE_REPO: "https://raw.githubusercontent.com/4d-for-ios/check-workflow/master"
      steps:
        - name: â¬‡ï¸ Checkout
          uses: actions/checkout@master
          with:
            fetch-depth: 1
        - name: ğŸ‘· Swift build
          run: |
            cd ios
            curl -fsSL $RELEASE_REPO/form/scripts/swift_build.sh | bash -s
